#
#  Copyright 2015 VMware, Inc.  All rights reserved.
#  SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: depoloy vRealize Operations Manager OVA
  include: vropsova_deploy.yml tags=vropsova_deploy

- name: initialize vRealize Operations Manager admin user
  include: vrops_admin_init.yml tags=vrops_admin_init

- name: initialize vRealize Operations Manager
  include: vrops_master_init.yml tags=vrops_master_init

- name: initialize vRealize Operations Manager cluster members
  include: vrops_cluster_init.yml tags=vrops_cluster_init
