#
#  Copyright 2015 VMware, Inc.  All rights reserved.
#  SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: create cluster name request
  template:
    src: cluster-name-body.json
    dest: "{{ cluster_name_body_file }}"
  tags:
    - vrops_init

- debug: msg="{{ lookup('file',cluster_name_body_file) }}"
  tags:
    - vrops_master_init

- name: configure cluster name
  uri:
    url: https://{{ vrops_master_node_ip }}/casa/deployment/cluster/info
    method: PUT
    user: "{{ default_admin_user }}"
    password: "{{ svc_vrops_admin_password }}"
    force_basic_auth: yes
    HEADER_Content-Type: "application/json"
    body: "{{ lookup('file',cluster_name_body_file) }}"
    validate_certs: no
    status_code: 200
  tags:

- name: create slice name request
  template:
    src: slice-name-body.json
    dest: "{{ slice_name_body_file }}"
  tags:
    - vrops_master_init

- debug: msg="{{ lookup('file',slice_name_body_file) }}"
  tags:
    - vrops_master_init

- name: configure slice name
  uri:
    url: https://{{ vrops_master_node_ip }}/casa/deployment/slice/{{ vrops_master_node_ip }}
    method: PUT
    user: "{{ default_admin_user }}"
    password: "{{ svc_vrops_admin_password }}"
    force_basic_auth: yes
    HEADER_Content-Type: "application/json"
    body: "{{ lookup('file',slice_name_body_file) }}"
    validate_certs: no
    status_code: 200
  tags:
    - vrops_master_init

- name: get cluster state
  uri:
    url: https://{{ vrops_master_node_ip }}/casa/deployment/cluster/info
    user: "{{ default_admin_user }}"
    password: "{{ svc_vrops_admin_password }}"
    force_basic_auth: yes
    HEADER_Content-Type: "application/json"
    validate_certs: no
    status_code: 200
  register: cluster_info_response
  tags:
    - vrops_master_init

- name: initialize cluster
  uri:
    url: https://{{ vrops_master_node_ip }}/casa/deployment/cluster/initialization?async=false
    method: POST
    user: "{{ default_admin_user }}"
    password: "{{ svc_vrops_admin_password }}"
    force_basic_auth: yes
    HEADER_Content-Type: "application/json"
    validate_certs: no
    timeout: 3600
    status_code: 200
  when: cluster_info_response.json.installation_state == 'NEW'
  tags:
    - vrops_master_init
